### ISSUE TITLE
symbol lookup error on ROS2 jazzy

### ISSUE THREAD

**Issue by Tacha-S** [mikeferguson/robot_calibration#170]
When I run a package installed with apt, the following error occurs.

```bash
[calibrate-1] /opt/ros/jazzy/lib/robot_calibration/calibrate: symbol lookup error: /opt/ros/jazzy/lib/librobot_calibration_feature_finders.so: undefined symbol: _ZN3tf212getTimestampIN13geometry_msgs3msg13PointStamped_ISaIvEEEEENSt6chrono10time_pointINS6_3_V212system_clockENS6_8durationIlSt5ratioILl1ELl1000000000EEEEEERKT_
```

**Comment by mikeferguson** [comment]
Interesting - I haven't run into this. Which feature finders are you using?

```
std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > tf2::getTimestamp<geometry_msgs::msg::PointStamped_<std::allocator<void> > >(geometry_msgs::msg::PointStamped_<std::allocator<void> > const&)
```

**Comment by Tacha-S** [comment]
I am using `robot_calibration::PlaneFinder` and `robot_calibration::ScanFinder`. When I installed them via apt, I encountered a symbol lookup error, but the error did not occur when I built them from source. There might be an issue with the apt package's binary.

**Comment by mikeferguson** [comment]
Ok, so returning to looking at this:

 * getTimestamp() is inlined (and templated)
 * internally it calls tf2_ros::fromMsg - which is also inlined and templated
 * nm/ldd don't seem to show any issues with calibrate, librobot_calibration, or librobot_calibration_feature_finders on my AMD64 install of most recent jazzy binaries.

Are you on some different platform? Something other than AMD64 on Ubuntu 24.04?

**Comment by Tacha-S** [comment]
I'm executing on AMD64 with Ubuntu 24.04, just like you.

**Comment by mikeferguson** [comment]
I put a new release out for Jazzy+Rolling yesterday which includes the fixes I need to be able to run calibration on my robot - as soon as those get built I'll try out the debs and try to figure out what is going on

**Comment by mikeferguson** [comment]
Have reproduced this locally:

 * Jazzy deb is missing the symbol
 * Totally up-to-date 24.04 source build has the symbol
 * Iron deb is also missing the symbol
 * Humble deb is also missing the symbol

Building with -DCMAKE_BUILD_TYPE=None (as debs are), still generates the symbols...

But building with -DCMAKE_BUILD_TYPE=RelWithDebInfo gets the missing symbols (and harks back to a similar issue I had here: https://github.com/mikeferguson/graceful_controller/issues/52)

This missing (inline) function is being used in tf2_buffer_->transform(), so we can go find where that was included (include/feature_finder.hpp) and move the geometry_msgs import ahead of that - and voila, our RelWithDebInfo build no longer has the undefined symbol (in fact, symbol is entirely gone - which is what i would expect since it is inline).

**Comment by mikeferguson** [comment]
Iron/Jazzy/Rolling fix should be: https://github.com/mikeferguson/robot_calibration/pull/182 (and a new release)

Humble backport: https://github.com/mikeferguson/robot_calibration/pull/183

**Comment by mikeferguson** [comment]
I just grabbed the latest Debian build of 0.9.2 for Iron from the ros2-testing - the missing symbol issue is resolved. This problem will go away fully once the next sync happens for Humble, Iron, Jazzy and Rolling distributions
