### ISSUE TITLE
Use of Joint States in Led Finder

### ISSUE THREAD

**Issue by saurabhbansal90** [mikeferguson/robot_calibration#66]
Hello Mark,

I have seen in the code that joint states are being captured along with sensors observations.
Can you please let me know if there is any use joint states, when we use led-finder for calibration.

The reason I am asking this question is that, I was trying yo calibrate my Arm, but during optimisation, I am getting below INTIAL_COST also:
`[ INFO] [1548670250.287325912]: Done capturing samples
[ INFO] [1548670250.458293943]: Creating chain 'arm' from base_link to link9
[ INFO] [1548670250.458999058]: Creating chain 'camera' from base_link to camera_depth_optical_frame
[ INFO] [1548670250.459494857]: optimize: number of  offsets: 18
[ INFO] [1548670250.460143902]: Diff. X: -0.014663, Y: -0.008728, Z: -0.013612
INITIAL COST (0)
  x:    -0.014663
  y:    -0.008728
  z:    -0.013612

[ INFO] [1548670255.473269566]: Diff. X: -0.010441, Y: -0.030350, Z: -0.009042
INITIAL COST (1)
  x:    -0.010441
  y:    -0.030350
  z:    -0.009042

[ INFO] [1548670256.158610420]: Diff. X: -0.018447, Y: -0.007326, Z: -0.012469
INITIAL COST (2)
  x:    -0.018447
  y:    -0.007326
  z:    -0.012469

[ INFO] [1548670256.755370759]: Diff. X: -0.011827, Y: -0.028897, Z: -0.006128
INITIAL COST (3)
  x:    -0.011827
  y:    -0.028897
  z:    -0.006128

[ INFO] [1548670257.349901199]: Diff. X: -0.016052, Y: -0.000944, Z: -0.014128
INITIAL COST (4)
  x:    -0.016052
  y:    -0.000944
  z:    -0.014128

[ INFO] [1548670268.770670017]: Diff. X: -0.015684, Y: -0.027633, Z: -0.005686
INITIAL COST (5)
  x:    -0.015684
  y:    -0.027633
  z:    -0.005686

[ INFO] [1548670270.316994017]: Diff. X: -0.017168, Y: -0.006394, Z: -0.012698
INITIAL COST (6)
  x:    -0.017168
  y:    -0.006394
  z:    -0.012698

[ INFO] [1548670270.805101483]: Diff. X: -0.009859, Y: -0.029202, Z: -0.009290
INITIAL COST (7)
  x:    -0.009859
  y:    -0.029202
  z:    -0.009290

[ INFO] [1548670271.236804588]: Diff. X: -0.014154, Y: -0.008500, Z: -0.014610
INITIAL COST (8)
  x:    -0.014154
  y:    -0.008500
  z:    -0.014610

[ INFO] [1548670271.692414772]: Diff. X: -0.012408, Y: -0.029938, Z: -0.006983
INITIAL COST (9)
  x:    -0.012408
  y:    -0.029938
  z:    -0.006983

[ INFO] [1548670272.160246525]: Diff. X: -0.018766, Y: -0.012255, Z: -0.012287
INITIAL COST (10)
  x:    -0.018766
  y:    -0.012255
  z:    -0.012287

[ INFO] [1548670272.694415553]: Diff. X: -0.011520, Y: -0.028422, Z: -0.010442
INITIAL COST (11)
  x:    -0.011520
  y:    -0.028422
  z:    -0.010442

[ INFO] [1548670273.410029176]: Diff. X: -0.020646, Y: -0.022069, Z: -0.005931
INITIAL COST (12)
  x:    -0.020646
  y:    -0.022069
  z:    -0.005931

[ INFO] [1548670273.905140344]: Diff. X: -0.012245, Y: -0.025323, Z: -0.011808
INITIAL COST (13)
  x:    -0.012245
  y:    -0.025323
  z:    -0.011808

[ INFO] [1548670275.668234342]: Diff. X: -0.023359, Y: -0.017796, Z: -0.004427
INITIAL COST (14)
  x:    -0.023359
  y:    -0.017796
  z:    -0.004427

`
The INITIAL_COST is  quite low only, but I am getting huge variations in my generated URDF.
Even though I  checked the Joint states, they seems to be correct only.

Can you please, give me a hint, why  I should be getting so huge variations in generated URDF.

Regards,
Saurabh

**Comment by mikeferguson** [comment]
@saurabhbansal90 Apologies on delayed response, just getting back from out of office.

The joint states are always used -- we need them to know the configuration of the kinematic chain (where the arm/head is for a given set of sensor observations).

Are you using a single LED? I've never had good results with a single LED -- the Fetch/UBR both had a pattern of 4 leds so that rotation of the wrist joint can be determined. The PR2 actually had a single LED and we never used it because it did not provide enough data (further, it was on-axis with the wrist roll joint, so it gave even less rotation data than if it had been significantly off-axis. we always used checkerboards with the PR2 calibration). If you are trying to use a single LED, I'd suggest you need MANY samples (it appears you have 14 -- I would suggest a single LED might need 100-200 samples to have any hope of working).

With only a single LED and only 14 samples, I could definitely see things getting overfit to the data (which could result in really wonky URDF changes). It's possible to try and cancel this out with the use of an "outrageous error block" -- which basically adds an error term for how much a given joint offset changes, but the better approach would be to add more samples, and change to a checkerboard or multiple LED pattern. (For reference, with the Fetch robot, which has 9 joints under calibration (7 arm Dofs + 2 head dofs) along with a 6-dof pose of the camera link, we needed about 50-70 well-distributed poses to get good results, maybe 10-15 less for a checkerboard).

**Comment by saurabhbansal90** [comment]
Hello Mike,

Thanks for the response, actually I was there at our field visit. So was not able to reply back, sorry for that.
Actually we were not using the LED's, but a similar program using a marker. The reason was that, the LED finder program was not able to detect the depth of LED point, as we were using a Stereo Camera, instead of IR camera.
So we made a marker, a unique pattern and tied that with the tip of our arm, and was detecting its xyz location and performed calibration.
I was using 14-15 points and 3 joints for calibration, and by god'd grace it was all working fine.

After that, there were few changes in the mechanical design and so in URDF.
After that something gone bad with calibration, and till now I am not able to make it work again.
To add more points and to be able to calibrate in open field also, I used Aruco pattern in the marker.

So now I have 4 points in one observation. And point number are same as 15, and number of joints to be calibrated is also same i.e. 3 joints.
But I am getting very vague values. I tried to print the value of INITIAL COST also, that seems to be fine.
But still not able to get good calibrated URDF.

I am not sure if its a problem with local minima. Can you please suggest some methods to  debug and to find the problem with my configuration or somewhere.
Or is there any method to print the value of cost function so that I  can check if its stuck in a local minima.

Regards,
Saurabh
